# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 80e122b4e4d98126233e1e9238e4918ababdc27c653912ab5cf40e5376cbc85c79143e2491d743a551804d6ad52593789e85188bd3bd51df16579059ba5dc09b

test:
  secret_key_base: 623245b2c6c5dcc0f7c6e8617103a80ba65e4539279c6cb78e5fb5c6436d7c77efe24b2d3bba6afeac33af4b7e89db84b8d07e671bfa03edd613bd6d1090a3fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
